# Generated by Django 3.2.6 on 2021-08-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_student_student_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_Address',
        ),
        migrations.AlterField(
            model_name='student',
            name='School_Name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='demo.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_File',
            field=models.FileField(default=0, upload_to='pdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Roll_No',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='Teacher_Name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='demo.teacher'),
            preserve_default=False,
        ),
    ]
